// frontend/src/views/WorkflowsView.vue
<script setup lang="ts">
// Workflows top-level view — port of WorkflowsView.jsx: exactly 3 sub-views
// reached via a ViewSwitcher pill (Workflows / Script & OMA-URI Library /
// Firewall Policy Library — NOT the 6 flat tabs this file used to have).
// "Recent runs" lives inline below the workflow grid on the Workflows tab,
// not as a separate tab. Script Repos has no persistent tab in the
// original — it's a modal reached from the Library tab's "Import from Git
// repo" button. Triggers is not part of this view at all in the original —
// it's Settings' "Inbound Webhooks" tab; moved there in this same pass.
import { Alert } from "@applivery/bluesky-vue";
import { computed, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { ICONS } from "../lib/solarIcons";
import HelpIcon from "../components/shared/HelpIcon.vue";
import DryRunDialog from "../components/workflows/DryRunDialog.vue";
import RecentRunsSection from "../components/workflows/RecentRunsSection.vue";
import RunWorkflowDialog from "../components/workflows/RunWorkflowDialog.vue";
import VersionHistoryModal from "../components/workflows/VersionHistoryModal.vue";
import WorkflowBuilderModal from "../components/workflows/WorkflowBuilderModal.vue";
import WorkflowsTable from "../components/workflows/WorkflowsTable.vue";
import ActionLibraryTable from "../components/workflows/ActionLibraryTable.vue";
import ActionLibraryEntryDialog from "../components/workflows/ActionLibraryEntryDialog.vue";
import ScriptBrowseImportDialog from "../components/workflows/ScriptBrowseImportDialog.vue";
import ScriptRepoImportModal from "../components/workflows/ScriptRepoImportModal.vue";
import FirewallRuleSetsTable from "../components/workflows/FirewallRuleSetsTable.vue";
import FirewallRuleSetBuilderDrawer from "../components/workflows/FirewallRuleSetBuilderDrawer.vue";
import { useWorkflowsStore, type Workflow } from "../stores/workflows";
import { useActionLibraryStore, type ActionLibraryEntry } from "../stores/actionLibrary";
import { useFirewallRuleSetsStore, type FirewallRuleSet } from "../stores/firewallRuleSets";

const store = useWorkflowsStore();
const actionLibraryStore = useActionLibraryStore();
const firewallStore = useFirewallRuleSetsStore();
const route = useRoute();
const router = useRouter();

type Tab = "workflows" | "library" | "firewall";
const tab = ref<Tab>("workflows");
// Port of WORKFLOWS_TAB_ANCHORS (WorkflowsView.jsx:11).
const WORKFLOWS_TAB_ANCHORS: Record<Tab, string> = {
  workflows: "workflow-list", library: "script--oma-uri-library", firewall: "firewall-policy-library",
};
const helpAnchor = computed(() => WORKFLOWS_TAB_ANCHORS[tab.value]);

const builderOpen = ref(false);
const editingWorkflow = ref<Workflow | null>(null);
const dryRunOpen = ref(false);
const runDialogOpen = ref(false);
const versionsOpen = ref(false);
const activeWorkflow = ref<Workflow | null>(null);

const libraryEntryOpen = ref(false);
const editingEntry = ref<ActionLibraryEntry | null>(null);
const browseApplivertOpen = ref(false);
const scriptRepoImportOpen = ref(false);

const firewallBuilderOpen = ref(false);
const editingRuleSet = ref<FirewallRuleSet | null>(null);

// Platform filter for the Workflows list — mirrors ComplianceView.vue's own
// policyPlatformFilter (same option set/labels, same "common" = no
// targetPlatform distinction), added per user request for parity between
// the two views.
const WORKFLOW_PLATFORM_FILTER_OPTIONS: Array<{ value: string; label: string }> = [
  { value: "", label: "All platforms" },
  { value: "common", label: "Common (all platforms)" },
  { value: "apple", label: "iOS/iPadOS" },
  { value: "macos", label: "macOS" },
  { value: "android", label: "Android" },
  { value: "windows", label: "Windows" },
  { value: "aosp", label: "AOSP" },
];
const workflowPlatformFilter = ref("");
const visibleWorkflows = computed(() => {
  if (workflowPlatformFilter.value === "common") return store.workflows.filter((w) => !w.targetPlatform);
  if (workflowPlatformFilter.value) return store.workflows.filter((w) => w.targetPlatform === workflowPlatformFilter.value);
  return store.workflows;
});

function openNew() {
  editingWorkflow.value = null;
  builderOpen.value = true;
}
function openEdit(w: Workflow) {
  editingWorkflow.value = w;
  builderOpen.value = true;
}
function openDryRun(w: Workflow) {
  activeWorkflow.value = w;
  dryRunOpen.value = true;
}
function openRun(w: Workflow) {
  activeWorkflow.value = w;
  runDialogOpen.value = true;
}
function openVersions(w: Workflow) {
  activeWorkflow.value = w;
  versionsOpen.value = true;
}

function openNewLibraryEntry() {
  editingEntry.value = null;
  libraryEntryOpen.value = true;
}
function openEditLibraryEntry(e: ActionLibraryEntry) {
  editingEntry.value = e;
  libraryEntryOpen.value = true;
}

function openNewRuleSet() {
  editingRuleSet.value = null;
  firewallBuilderOpen.value = true;
}
function openEditRuleSet(r: FirewallRuleSet) {
  editingRuleSet.value = r;
  firewallBuilderOpen.value = true;
}

async function selectTab(t: Tab) {
  tab.value = t;
  if (t === "library" && actionLibraryStore.entries.length === 0) await actionLibraryStore.fetchEntries();
  if (t === "firewall" && firewallStore.ruleSets.length === 0) await firewallStore.fetchRuleSets();
}

onMounted(async () => {
  await store.fetchWorkflows();
  // Arrived via a cross-link (Compliance's Workflow-column icon click) —
  // auto-open that workflow's builder in edit mode, same query-param
  // pattern as Devices' ?deviceId= and Cases' ?caseId=. Cleared from the
  // URL immediately after so a manual refresh doesn't keep re-opening it.
  const editWorkflowId = route.query.editWorkflowId;
  if (typeof editWorkflowId === "string" && editWorkflowId) {
    const target = store.workflows.find((w) => w.id === editWorkflowId);
    if (target) openEdit(target);
    router.replace({ path: "/workflows", query: {} });
  }
});
</script>

<template>
  <main class="p-4 md:p-8 pb-16">
    <header class="flex justify-between items-start mb-8 gap-4 flex-wrap">
      <div>
        <div class="flex items-center gap-2">
          <h1 class="text-2xl font-semibold leading-tight text-gray-900 dark:text-white">Workflows</h1>
          <HelpIcon slug="workflows" :anchor="helpAnchor" title="Workflows admin guide" />
        </div>
        <p class="text-sm mt-1 text-gray-400">
          Chained actions — MDM commands, API calls, and notifications. Run manually, auto-fired by Compliance Policies on violation, or launched directly from a Case.
        </p>
      </div>
    </header>

    <!-- Full-width toolbar row (matches ComplianceView.vue's layout): the
         platform filter sits flush left, Create Workflow + the sub-view pill
         switcher stay grouped on the right, in that order — per user
         request to match the left/right split used elsewhere. -->
    <div class="flex items-center justify-between gap-3 flex-wrap mb-8">
      <!-- Same invisible/reserved-space trick as the Create Workflow button
           to the right — only meaningful on the Workflows tab, but kept in
           the layout (rather than v-if'd out) on the other two tabs so the
           toolbar row's width doesn't jump when switching tabs. -->
      <select
        v-model="workflowPlatformFilter"
        title="Filter the Workflows list to one platform"
        class="px-2.5 py-2 rounded-lg text-sm font-medium outline-none border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 focus:ring-2 focus:ring-brand-500 shrink-0"
        :class="tab === 'workflows' ? '' : 'invisible pointer-events-none'"
        :aria-hidden="tab !== 'workflows'"
        :tabindex="tab === 'workflows' ? 0 : -1"
      >
        <option v-for="p in WORKFLOW_PLATFORM_FILTER_OPTIONS" :key="p.value" :value="p.value">{{ p.label }}</option>
      </select>
      <div class="flex flex-wrap items-center gap-2 shrink-0">
        <!-- Always rendered (rather than conditionally mounted) so its layout
             space stays reserved on non-Workflows tabs — otherwise the pill
             switcher next to it visibly shifts position, since removing this
             button changes the row's total width. Port of the original's
             identical `invisible pointer-events-none` trick. -->
        <button
          class="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium text-white bg-brand-600 hover:bg-brand-700 transition-all duration-200 shrink-0"
          :class="tab === 'workflows' ? '' : 'invisible pointer-events-none'"
          :aria-hidden="tab !== 'workflows'"
          :tabindex="tab === 'workflows' ? 0 : -1"
          @click="openNew"
        >
          <component :is="ICONS.AddSquare" :size="15" weight="Linear" /> Create Workflow
        </button>
        <div class="flex items-center gap-1 p-1 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900/50 shrink-0 max-w-full overflow-x-auto">
          <button
            class="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-all"
            :class="tab === 'workflows' ? 'bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm' : 'text-gray-400'"
            @click="selectTab('workflows')"
          >
            <component :is="ICONS.Structure" :size="14" weight="Linear" /> Workflows
          </button>
          <button
            class="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-all"
            :class="tab === 'library' ? 'bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm' : 'text-gray-400'"
            @click="selectTab('library')"
          >
            <component :is="ICONS.Library" :size="14" weight="Linear" /> Script &amp; OMA-URI Library
          </button>
          <button
            class="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-all"
            :class="tab === 'firewall' ? 'bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm' : 'text-gray-400'"
            @click="selectTab('firewall')"
          >
            <component :is="ICONS.ShieldCheck" :size="14" weight="Linear" /> Firewall Policy Library
          </button>
        </div>
      </div>
    </div>

    <template v-if="tab === 'library'">
      <Alert v-if="actionLibraryStore.error" type="danger">{{ actionLibraryStore.error }}</Alert>
      <ActionLibraryTable
        :entries="actionLibraryStore.entries"
        :is-loading="actionLibraryStore.isLoading"
        @edit="openEditLibraryEntry"
        @new="openNewLibraryEntry"
        @fetch-applivery="browseApplivertOpen = true"
        @import-git-repo="scriptRepoImportOpen = true"
      />
    </template>
    <template v-else-if="tab === 'firewall'">
      <Alert v-if="firewallStore.error" type="danger">{{ firewallStore.error }}</Alert>
      <FirewallRuleSetsTable :rule-sets="firewallStore.ruleSets" :is-loading="firewallStore.isLoading" @edit="openEditRuleSet" @new="openNewRuleSet" />
    </template>
    <template v-else>
      <Alert v-if="store.error" type="danger">{{ store.error }}</Alert>
      <WorkflowsTable :workflows="visibleWorkflows" :is-loading="store.isLoading" @edit="openEdit" @dry-run="openDryRun" @run="openRun" @versions="openVersions" />
      <RecentRunsSection />
    </template>

    <WorkflowBuilderModal :open="builderOpen" :workflow="editingWorkflow" @close="builderOpen = false" @saved="store.fetchWorkflows()" />
    <DryRunDialog :open="dryRunOpen" :workflow="activeWorkflow" @close="dryRunOpen = false" />
    <RunWorkflowDialog :open="runDialogOpen" :workflow="activeWorkflow" @close="runDialogOpen = false" />
    <VersionHistoryModal :open="versionsOpen" :workflow="activeWorkflow" @close="versionsOpen = false" @restored="store.fetchWorkflows()" />

    <ActionLibraryEntryDialog :open="libraryEntryOpen" :entry="editingEntry" @close="libraryEntryOpen = false" @saved="actionLibraryStore.fetchEntries()" />
    <ScriptBrowseImportDialog :open="browseApplivertOpen" @close="browseApplivertOpen = false" @imported="actionLibraryStore.fetchEntries()" />
    <ScriptRepoImportModal :open="scriptRepoImportOpen" @close="scriptRepoImportOpen = false" @imported="actionLibraryStore.fetchEntries()" />

    <FirewallRuleSetBuilderDrawer :open="firewallBuilderOpen" :rule-set="editingRuleSet" @close="firewallBuilderOpen = false" @saved="firewallStore.fetchRuleSets()" />
  </main>
</template>

// wow-dashboard/src/components/workflows/WorkflowsView.jsx
import React, { useState, useEffect, useCallback } from 'react';
import axios from 'axios';
import { AddSquare as Plus, Structure as Workflow, Pen, TrashBinMinimalistic as Trash2, Play, DangerTriangle as AlertTriangle, History, CheckCircle as CheckCircle2, CloseCircle as XCircle, MinusCircle, Refresh as Loader2, ClockCircle as Clock, Library, TestTube, Download, ShieldCheck } from '@solar-icons/react';
import WorkflowBuilder from './WorkflowBuilder';
import { DevicePickerModal, WorkflowRunResultModal, DryRunModal, WorkflowVersionsModal } from './WorkflowRunModals';
import ActionLibraryView from './ActionLibraryView';
import FirewallLibraryView from './FirewallLibraryView';
import ViewSwitcher from '../shared/ViewSwitcher';
import HelpIcon from '../shared/HelpIcon';

// Heading ids inside docs/workflows.md for each sub-view tab.
const WORKFLOWS_TAB_ANCHORS = { workflows: 'workflow-list', library: 'script--oma-uri-library', firewall: 'firewall-policy-library' };

const PRIMARY_BLUE = '#0241E3';
const SUCCESS = '#22C55E';
const DANGER = '#EF4444';
const WARNING = '#F59E0B';

const PLATFORM_LABELS = { apple: 'iOS', macos: 'macOS', android: 'Android', windows: 'Windows', aosp: 'AOSP' };
const MODEL_LABELS = {
  supervised: 'Supervised', unsupervised: 'Unsupervised',
  work_profile: 'Work Profile', cope: 'COPE', device_owner: 'Device Owner',
};

function runStatusMeta(run) {
  if (run.status === 'running') return { color: PRIMARY_BLUE, Icon: Loader2, label: `Running ${run.completed ?? 0}/${run.total ?? '?'}`, spin: true };
  // Durable engine: one or more devices are parked at a 'wait' step,
  // possibly for hours/days — the run stays open (not yet in history)
  // until the resumer loop finishes every device.
  if (run.status === 'waiting') return { color: PRIMARY_BLUE, Icon: Clock, label: `Waiting ${run.completed ?? 0}/${run.total ?? '?'}`, spin: false };
  const statuses = (run.results || []).map(r => r.finalStatus);
  if (statuses.length && statuses.every(s => s === 'success')) return { color: SUCCESS, Icon: CheckCircle2, label: 'Completed' };
  if (statuses.some(s => s === 'success' || s === 'partial')) return { color: WARNING, Icon: MinusCircle, label: 'Partial' };
  return { color: DANGER, Icon: XCircle, label: 'Failed' };
}

export default function WorkflowsView({ apiToken, orgSlug, theme, canDelete = true, canRunDestructive = true }) {
  const [workflows, setWorkflows] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);
  const [builderWorkflow, setBuilderWorkflow] = useState(undefined); // undefined = closed, null = new, object = edit
  const [runningWorkflow, setRunningWorkflow] = useState(null);
  const [runResult, setRunResult] = useState(null);
  const [dryRunWorkflow, setDryRunWorkflow] = useState(null);
  const [historyWorkflow, setHistoryWorkflow] = useState(null);
  const [recentRuns, setRecentRuns] = useState([]);
  const [runsLimit, setRunsLimit] = useState(10);
  const [runDateFrom, setRunDateFrom] = useState('');
  const [runDateTo, setRunDateTo] = useState('');
  const [tab, setTab] = useState('workflows'); // 'workflows' | 'library' | 'firewall'

  const headers = { Authorization: `Bearer ${apiToken}`, 'X-Workspace-Slug': orgSlug };

  const fetchWorkflows = useCallback(async () => {
    if (!apiToken || !orgSlug) return;
    setIsLoading(true);
    setError(null);
    try {
      const res = await axios.get('/api/workflows', { headers });
      setWorkflows(res.data?.items || []);
    } catch (err) {
      setError(err.response?.data?.detail || 'Failed to load workflows.');
    } finally {
      setIsLoading(false);
    }
  }, [apiToken, orgSlug]);

  const fetchRecentRuns = useCallback(async (limit) => {
    if (!apiToken || !orgSlug) return;
    try {
      const params = { limit: limit || runsLimit };
      if (runDateFrom) params.date_from = runDateFrom;
      if (runDateTo) params.date_to = runDateTo;
      const res = await axios.get('/api/workflows/runs', { headers, params });
      setRecentRuns(res.data?.items || []);
    } catch {
      // non-critical — history is a nice-to-have
    }
  }, [apiToken, orgSlug, runsLimit, runDateFrom, runDateTo]);

  useEffect(() => { fetchWorkflows(); }, [fetchWorkflows]);
  useEffect(() => { fetchRecentRuns(); }, [fetchRecentRuns]);

  function handleExportRuns() {
    const params = new URLSearchParams();
    if (runDateFrom) params.set('date_from', runDateFrom);
    if (runDateTo) params.set('date_to', runDateTo);
    axios.get(`/api/workflows/runs/export?${params}`, { headers, responseType: 'blob' }).then(res => {
      const blobUrl = window.URL.createObjectURL(new Blob([res.data]));
      const a = document.createElement('a');
      a.href = blobUrl;
      a.download = 'workflow-runs.csv';
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(blobUrl);
    }).catch(() => alert('Failed to export workflow runs.'));
  }

  async function handleDelete(workflow) {
    if (!window.confirm(`Delete workflow "${workflow.name}"? This cannot be undone.`)) return;
    await axios.delete(`/api/workflows/${workflow.id}`, { headers });
    fetchWorkflows();
  }

  function handleSaved() {
    setBuilderWorkflow(undefined);
    fetchWorkflows();
  }

  async function handleRunConfirm(devices, targetDescription) {
    try {
      const res = await axios.post(`/api/workflows/${runningWorkflow.id}/run`, {
        devices: devices.map(d => ({
          id: d.id, displayName: d.displayName, platform: d.platform, platformDeviceId: d.platformDeviceId,
          serialNumber: d.serialNumber, osVersion: d.osVersion, manufacturer: d.manufacturer, model: d.model,
          udid: d.udid, mdmUser: d.mdmUser,
        })),
        targetDescription: targetDescription || null,
      }, { headers });
      // Response returns immediately (status: 'running') — the result modal polls for progress.
      setRunningWorkflow(null);
      setRunResult(res.data);
      fetchRecentRuns();
    } catch (err) {
      alert(err.response?.data?.detail || 'Failed to run workflow.');
    }
  }

  return (
    <main className="p-8 pb-16 flex-1 relative overflow-y-auto">
      <header className="flex justify-between items-start mb-8 gap-4 flex-wrap">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl font-semibold leading-tight" style={{ color: theme.text }}>Workflows</h1>
            <HelpIcon slug="workflows" anchor={WORKFLOWS_TAB_ANCHORS[tab]} theme={theme} title="Workflows admin guide" />
          </div>
          <p className="text-sm mt-1" style={{ color: theme.textMuted }}>
            Chained actions — MDM commands, API calls, and notifications. Run manually, auto-fired by Compliance Policies on violation, or launched directly from a Case.
          </p>
        </div>
        <div className="flex items-center gap-2 shrink-0 ml-auto">
          <ViewSwitcher
            theme={theme}
            active={tab}
            onChange={setTab}
            tabs={[
              { id: 'workflows', label: 'Workflows', Icon: Workflow },
              { id: 'library',   label: 'Script & OMA-URI Library', Icon: Library },
              { id: 'firewall',  label: 'Firewall Policy Library', Icon: ShieldCheck },
            ]}
          />
          {/* Always rendered (rather than conditionally mounted) so its layout
              space stays reserved even on the Library tab — otherwise the
              ViewSwitcher next to it visibly shifts position depending on
              which tab is active, since removing this button changes the
              row's total width. */}
          <button
            onClick={() => setBuilderWorkflow(null)}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium text-white bg-brand-600 transition-all duration-200 hover:bg-brand-700 shrink-0 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2 ${tab === 'workflows' ? '' : 'invisible pointer-events-none'}`}
            aria-hidden={tab !== 'workflows'}
            tabIndex={tab === 'workflows' ? 0 : -1}
          >
            <Plus size={15} /> Create Workflow
          </button>
        </div>
      </header>

      {tab === 'library' ? (
        <ActionLibraryView apiToken={apiToken} orgSlug={orgSlug} theme={theme} />
      ) : tab === 'firewall' ? (
        <FirewallLibraryView apiToken={apiToken} orgSlug={orgSlug} theme={theme} />
      ) : isLoading ? (
        <div className="flex flex-col items-center justify-center min-h-[300px]">
          <div className="w-8 h-8 border-2 rounded-full animate-spin mb-4" style={{ borderColor: `${PRIMARY_BLUE}30`, borderTopColor: PRIMARY_BLUE }} />
          <span className="text-xs uppercase tracking-widest font-bold" style={{ color: theme.textMuted }}>Loading workflows…</span>
        </div>
      ) : error ? (
        <div className="flex items-start gap-3 px-4 py-3 rounded-xl" style={{ backgroundColor: `${DANGER}10`, border: `1px solid ${DANGER}30` }}>
          <AlertTriangle size={18} style={{ color: DANGER }} className="shrink-0 mt-0.5" />
          <p className="text-sm" style={{ color: DANGER }}>{error}</p>
        </div>
      ) : workflows.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 px-6 text-center rounded-xl" style={{ border: `1px dashed ${theme.border}` }}>
          <div className="w-12 h-12 rounded-2xl flex items-center justify-center mb-4" style={{ backgroundColor: theme.bg }}>
            <Workflow size={22} style={{ color: theme.textMuted }} />
          </div>
          <p className="text-sm font-semibold mb-1" style={{ color: theme.text }}>No workflows yet</p>
          <p className="text-sm max-w-xs" style={{ color: theme.textMuted }}>Create a chain of actions you can run against one or many devices.</p>
        </div>
      ) : (
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {workflows.map(p => {
            const hasDestructive = (p.steps || []).some(s => s.type === 'mdm_action');
            return (
              <div key={p.id} className="rounded-xl p-4 shadow-sm" style={{ backgroundColor: theme.card, border: `1px solid ${theme.border}` }}>
                <div className="flex items-start gap-2 mb-2">
                  <div className="w-9 h-9 rounded-lg flex items-center justify-center shrink-0" style={{ backgroundColor: `${PRIMARY_BLUE}12` }}>
                    <Workflow size={16} style={{ color: PRIMARY_BLUE }} />
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-semibold truncate" style={{ color: theme.text }}>{p.name}</p>
                    <p className="text-xs truncate flex items-center gap-1" style={{ color: theme.textMuted }}>
                      {p.steps?.length || 0} step{p.steps?.length === 1 ? '' : 's'}
                      {hasDestructive && (
                        <span className="inline-flex items-center gap-0.5" style={{ color: WARNING }} title="Includes MDM device actions">
                          <AlertTriangle size={10} /> MDM
                        </span>
                      )}
                      {hasDestructive && p.allowUnattendedDestructive && (
                        <span className="inline-flex items-center gap-0.5" style={{ color: SUCCESS }} title="Marked by its author as approved to run unattended — each Policy/Rule that fires it still needs its own separate acknowledgment">
                          <ShieldCheck size={10} /> Auto-run approved
                        </span>
                      )}
                    </p>
                  </div>
                </div>
                {p.targetPlatform && (
                  <span className="inline-flex items-center gap-1 mb-2 px-2 py-0.5 rounded-md text-[10px] font-semibold uppercase" style={{ backgroundColor: `${PRIMARY_BLUE}12`, color: PRIMARY_BLUE }}>
                    {PLATFORM_LABELS[p.targetPlatform] || p.targetPlatform}
                    {p.targetDeploymentModel && ` · ${MODEL_LABELS[p.targetDeploymentModel] || p.targetDeploymentModel}`}
                  </span>
                )}
                {p.description && <p className="text-xs mb-3 line-clamp-2" style={{ color: theme.textMuted }}>{p.description}</p>}
                <div className="flex items-center gap-2 mt-3">
                  <button
                    onClick={() => setRunningWorkflow(p)}
                    disabled={hasDestructive && !canRunDestructive}
                    title={hasDestructive && !canRunDestructive ? "Your role isn't permitted to run workflows with a destructive MDM step." : undefined}
                    className="flex-1 inline-flex items-center justify-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold text-white disabled:opacity-50 disabled:cursor-not-allowed"
                    style={{ backgroundColor: PRIMARY_BLUE }}
                  >
                    <Play size={12} /> Run
                  </button>
                  <button onClick={() => setDryRunWorkflow(p)} title="Dry run — safe preview, nothing is executed" className="p-1.5 rounded-lg" style={{ border: `1px solid ${theme.border}`, color: theme.textMuted }}>
                    <TestTube size={13} />
                  </button>
                  <button onClick={() => setHistoryWorkflow(p)} title="Version history" className="p-1.5 rounded-lg" style={{ border: `1px solid ${theme.border}`, color: theme.textMuted }}>
                    <History size={13} />
                  </button>
                  <button onClick={() => setBuilderWorkflow(p)} className="p-1.5 rounded-lg" style={{ border: `1px solid ${theme.border}`, color: theme.textMuted }}>
                    <Pen size={13} />
                  </button>
                  <button onClick={() => handleDelete(p)} disabled={!canDelete} title={!canDelete ? "Your role isn't permitted to delete Workflows." : undefined} className="p-1.5 rounded-lg disabled:opacity-40 disabled:cursor-not-allowed" style={{ border: `1px solid ${theme.border}`, color: DANGER }}>
                    <Trash2 size={13} />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {tab === 'workflows' && (
        <div className="mt-8">
          <div className="flex items-center justify-between flex-wrap gap-2 mb-3">
            <div className="flex items-center gap-2">
              <History size={14} style={{ color: theme.textMuted }} />
              <p className="text-xs font-semibold uppercase tracking-wider" style={{ color: theme.textMuted }}>Recent runs</p>
            </div>
            <div className="flex items-center gap-2">
              <input
                type="date"
                value={runDateFrom}
                onChange={(e) => setRunDateFrom(e.target.value)}
                className="px-2 py-1 rounded-lg text-xs outline-none focus:ring-2 focus:ring-brand-500"
                style={{ border: `1px solid ${theme.border}`, backgroundColor: theme.card, color: theme.text }}
              />
              <span className="text-xs" style={{ color: theme.textMuted }}>to</span>
              <input
                type="date"
                value={runDateTo}
                onChange={(e) => setRunDateTo(e.target.value)}
                className="px-2 py-1 rounded-lg text-xs outline-none focus:ring-2 focus:ring-brand-500"
                style={{ border: `1px solid ${theme.border}`, backgroundColor: theme.card, color: theme.text }}
              />
              <button
                onClick={handleExportRuns}
                className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-semibold"
                style={{ border: `1px solid ${theme.border}`, color: theme.text }}
              >
                <Download size={12} /> Export CSV
              </button>
            </div>
          </div>
          {recentRuns.length === 0 ? (
            <p className="text-xs py-4" style={{ color: theme.textMuted }}>No runs in this range yet.</p>
          ) : (
            <>
              <div className="rounded-xl overflow-hidden" style={{ border: `1px solid ${theme.border}` }}>
                {recentRuns.map((run, i) => {
                  const meta = runStatusMeta(run);
                  return (
                    <button
                      key={run.id}
                      onClick={() => setRunResult(run)}
                      className="w-full flex items-center gap-3 px-4 py-3 text-left transition-colors"
                      style={{ backgroundColor: theme.card, borderTop: i > 0 ? `1px solid ${theme.border}` : 'none' }}
                      onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = theme.bg; }}
                      onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = theme.card; }}
                    >
                      <meta.Icon size={14} style={{ color: meta.color }} className={meta.spin ? 'animate-spin' : ''} />
                      <div className="min-w-0">
                        <span className="text-sm font-medium truncate block" style={{ color: theme.text }}>{run.workflowName || 'Workflow'}</span>
                        {run.targetDescription && (
                          <span className="text-[11px] truncate block" style={{ color: theme.textMuted }}>{run.targetDescription}</span>
                        )}
                      </div>
                      <span className="text-xs shrink-0 ml-auto" style={{ color: theme.textMuted }}>
                        {run.total ?? run.results?.length ?? 0} device{(run.total ?? run.results?.length) === 1 ? '' : 's'}
                      </span>
                      <span className="text-xs shrink-0" style={{ color: meta.color }}>{meta.label}</span>
                    </button>
                  );
                })}
              </div>
              <button
                onClick={() => { const next = runsLimit + 20; setRunsLimit(next); fetchRecentRuns(next); }}
                className="mt-3 w-full py-2 rounded-lg text-xs font-semibold"
                style={{ border: `1px solid ${theme.border}`, color: theme.text }}
              >
                Show more
              </button>
            </>
          )}
        </div>
      )}

      {builderWorkflow !== undefined && (
        <WorkflowBuilder
          workflow={builderWorkflow}
          apiToken={apiToken}
          orgSlug={orgSlug}
          theme={theme}
          onClose={() => setBuilderWorkflow(undefined)}
          onSaved={handleSaved}
        />
      )}

      {runningWorkflow && (
        <DevicePickerModal
          apiToken={apiToken}
          orgSlug={orgSlug}
          theme={theme}
          onConfirm={handleRunConfirm}
          onClose={() => setRunningWorkflow(null)}
        />
      )}

      {runResult && (
        <WorkflowRunResultModal
          runRecord={runResult}
          apiToken={apiToken}
          orgSlug={orgSlug}
          theme={theme}
          onClose={() => setRunResult(null)}
          onComplete={fetchRecentRuns}
        />
      )}

      {dryRunWorkflow && (
        <DryRunModal
          workflow={dryRunWorkflow}
          apiToken={apiToken}
          orgSlug={orgSlug}
          theme={theme}
          onClose={() => setDryRunWorkflow(null)}
        />
      )}

      {historyWorkflow && (
        <WorkflowVersionsModal
          workflow={historyWorkflow}
          apiToken={apiToken}
          orgSlug={orgSlug}
          theme={theme}
          onClose={() => setHistoryWorkflow(null)}
          onRestored={fetchWorkflows}
        />
      )}
    </main>
  );
}
